In [63]:
import pandas as pd
import numpy as np
from tensorflow import keras
import tensorflow as tf

In [64]:
df = pd.read_csv('diamonds.csv')
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [65]:
missing_data = df.isnull().sum()
missing_data

Unnamed: 0    0
carat         0
cut           0
color         0
clarity       0
depth         0
table         0
price         0
x             0
y             0
z             0
dtype: int64

In [66]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['color'] = le.fit_transform(df['color'])
df['cut'] = le.fit_transform(df['cut'])
df['clarity'] = le.fit_transform(df['clarity'])
df.drop('Unnamed: 0', axis=1, inplace=True)

df.head(20)

    carat  cut  color  clarity  depth  table  price     x     y     z
0    0.23    2      1        3   61.5   55.0    326  3.95  3.98  2.43
1    0.21    3      1        2   59.8   61.0    326  3.89  3.84  2.31
2    0.23    1      1        4   56.9   65.0    327  4.05  4.07  2.31
3    0.29    3      5        5   62.4   58.0    334  4.20  4.23  2.63
4    0.31    1      6        3   63.3   58.0    335  4.34  4.35  2.75
5    0.24    4      6        7   62.8   57.0    336  3.94  3.96  2.48
6    0.24    4      5        6   62.3   57.0    336  3.95  3.98  2.47
7    0.26    4      4        2   61.9   55.0    337  4.07  4.11  2.53
8    0.22    0      1        5   65.1   61.0    337  3.87  3.78  2.49
9    0.23    4      4        4   59.4   61.0    338  4.00  4.05  2.39
10   0.30    1      6        2   64.0   55.0    339  4.25  4.28  2.73
11   0.23    2      6        4   62.8   56.0    340  3.93  3.90  2.46
12   0.22    3      2        2   60.4   61.0    342  3.88  3.84  2.33
13   0.31    2      6        3   62.2   54.0    344  4.35  4.37  2.71
14   0.20    3      1        3   60.2   62.0    345  3.79  3.75  2.27
15   0.32    3      1        0   60.9   58.0    345  4.38  4.42  2.68
16   0.30    2      5        3   62.0   54.0    348  4.31  4.34  2.68
17   0.30    1      6        2   63.4   54.0    351  4.23  4.29  2.70
18   0.30    1      6        2   63.8   56.0    351  4.23  4.26  2.71
19   0.30    4      6        2   62.7   59.0    351  4.21  4.27  2.66

In [67]:
from sklearn.preprocessing import MinMaxScaler

# Assuming 'data' is your dataset
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
# scaled_data

In [68]:
from sklearn.model_selection import train_test_split

x = df.drop('price', axis=1)  # Features
y = df['price']               # Target variable
x_train_main, x_test_main, y_train_main, y_test_main = train_test_split(x, y, test_size=0.1, random_state=42)

In [ ]:
from sklearn.metrics import mean_absolute_error


model = keras.Sequential()
model.add(keras.layers.Input(shape=(9,)))
model.add(keras.layers.Dense(units=32, activation='relu'))
model.add(keras.layers.Dense(units=32, activation='sigmoid'))
model.add(keras.layers.Dense(units=1))
model.compile(optimizer=tf.optimizers.Adam(), loss='mean_absolute_error', metrics=['accuracy'])
model.fit(x_train_main, y_train_main, epochs=20, batch_size=64, validation_data=(x_test_main, y_test_main))
y_pred = model.predict(x_test_main)
mse = mean_absolute_error(y_true=y_test_main, y_pred=y_pred)
mse

Epoch 1/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0000e+00 - loss: 3960.1892 - val_accuracy: 0.0000e+00 - val_loss: 3877.7893
Epoch 2/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0000e+00 - loss: 3915.2605 - val_accuracy: 0.0000e+00 - val_loss: 3862.4653
Epoch 3/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 3919.8262 - val_accuracy: 0.0000e+00 - val_loss: 3847.2400
Epoch 4/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0000e+00 - loss: 3907.6028 - val_accuracy: 0.0000e+00 - val_loss: 3832.0408
Epoch 5/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 3893.0913 - val_accuracy: 0.0000e+00 - val_loss: 3816.8535
Epoch 6/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0000e+00 - loss: 3838.2146 - val_accuracy: 0.0000e+00 - val_loss: 3801.6682
Epoch 7/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0000e+00 - loss: 3880.8464 - val_accuracy: 0.0000e+00 - val_loss: 3786.4895
Epoch 8/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0000e+00 - loss: 3794.0732 - val_accuracy: 0.0000e+00 - val_loss: 3771.3088
Epoch 9/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0000e+00 - loss: 3810.7268 - val_accuracy: 0.0000e+00 - val_loss: 3756.1309
Epoch 10/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0000e+00 - loss: 3788.8306 - val_accuracy: 0.0000e+00 - val_loss: 3739.0898
Epoch 11/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0000e+00 - loss: 3781.5781 - val_accuracy: 0.0000e+00 - val_loss: 3721.4873
Epoch 12/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0000e+00 - loss: 3789.2869 - val_accuracy: 0.0000e+00 - val_loss: 3704.5212
Epoch 13/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0000e+00 - loss: 3728.3403 - val_accuracy: 0.0000e+00 - val_loss: 3687.7092
Epoch 14/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0000e+00 - loss: 3728.2500 - val_accuracy: 0.0000e+00 - val_loss: 3670.9587
Epoch 15/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0000e+00 - loss: 3700.1335 - val_accuracy: 0.0000e+00 - val_loss: 3654.2307
Epoch 16/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0000e+00 - loss: 3651.3953 - val_accuracy: 0.0000e+00 - val_loss: 3637.5195
Epoch 17/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0000e+00 - loss: 3703.7288 - val_accuracy: 0.0000e+00 - val_loss: 3620.8083
Epoch 18/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0000e+00 - loss: 3657.7827 - val_accuracy: 0.0000e+00 - val_loss: 3604.1028
Epoch 19/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0000e+00 - loss: 3651.3748 - val_accuracy: 0.0000e+00 - val_loss: 3587.3987
Epoch 20/20
759/759 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0000e+00 - loss: 3613.6260 - val_accuracy: 0.0000e+00 - val_loss: 3570.6938
169/169 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

28896335.83170647

In [ ]:
# from sklearn.model_selection import KFold
# from sklearn.metrics import mean_squared_error


# kf = KFold(n_splits=6)
# def model_creator():
#     model = keras.Sequential()
#     model.add(keras.layers.Input(shape=(8,)))
#     model.add(keras.layers.Dense(units=448, activation='relu'))
#     model.add(keras.layers.Dense(units=320, activation='relu'))
#     model.add(keras.layers.Dense(units=32, activation='relu'))
#     model.add(keras.layers.Dense(units=1, activation='linear'))
#     model.compile(optimizer=tf.optimizers.Adam(), loss='mean_squared_error', metrics=['accuracy'])
#     return model



# # mse_list = []
# # for train, validation in kf.split(x_train_main, y_train_main):

# #     # x_train = x_train_main[train]
# #     # y_train = y_train_main[train]

# #     # x_test = x_train_main[validation]
# #     # y_test = x_train_main[validation]

# #     # x_train, x_test = x[train], x[validation]
# #     # y_train, y_test = y[train], y[validation]

# #     x_train = x_train_main[train]
# #     x_test = x_train_main[validation]
# #     y_train = y_train_main[train]
# #     y_test = y_train_main[validation]

# #     model = model_creator()
# #     model.fit(x_train, y_train, epochs=20, batch_size=64, validation_data=(x_test, y_test), verbose=0)

# #     y_pred = model.predict(x_test)

# #     mse_list.append(mean_squared_error(y_test, y_pred))

# # mse_list

# # y_pred_main = model.predict(x_test_main)
# # mse_main = mean_squared_error(y_test_main, y_pred_main)
# # mse_main, np.mean(mse_list)